version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432

    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: passwdtechstorm
      POSTGRES_DB: techstorm
    volumes:
      - ./Banco/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Banco/Persistencia:/data/postgres
    
    networks:
      - clima_rede

  nodejs:
    build: ./Node
    restart: always
    depends_on:
      - postgres
    networks:
      - clima_rede
    ports:
      - 4976:8080
    # Inicializacao
    command: "nodemon -x 'node app.js || touch app.js'"
    

networks:
  clima_rede: